### ISSUE TITLE
ARM_32bit: ValueError when starting build binary

### ISSUE THREAD

**Issue by cadlebe** [cadlebe/northwestclock.github.io#8]
**Describe the bug**
When running the binary build in Raspberry PI on Pi zero There is a ValueError: astimezone() cannot be applied to a naive datetime. [3220] Failed to execute script clock.

Traceback (most recent call last):
    File "clock.py", line 588, in <module>
    File "clock.py", line 82, in dateutc
    File "clock.py", line 63, in currenttime

**To Reproduce**
Run binary build for Pi Zero ARM_32-bit

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Version v0.2.11

**Comment by cadlebe** [comment]
My Pi has python 3.5 installed. Currently installing 3.7 to see if that might be the issue (I suspect this but have not other evidence other than 3.7 is what I use on my main system).
